title: "Sawa's blog on Card Games"
description: "A blog about Card Games and Related Topics"
url: "https://sawatcg.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.27.1"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
minimal_mistakes_skin: default

author:
  name: "Sawa"
  bio: " Player "

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
